// @generated by handbook/bin/gen-related-tools.mjs from handbook/tools.json — DO NOT EDIT.
// To change this tool's related-tools section, edit tools.json (this tool's `related[]`, or the
// referenced tools' hub.icon/hub.card), then run `node handbook/bin/gen-related-tools.mjs csv-viewer`
// (or with no arg to regenerate every active tool) and commit the result.

export interface RelatedToolCard {
  slug: string;
  icon: string;
  name: Record<string, string>;
  desc: Record<string, string>;
}

/** Curated related tools (Issue #177) — same hub.group baseline + genuine cross-group workflow ties. */
export const RELATED_TOOLS: RelatedToolCard[] = [
  {
    "slug": "xlsx-viewer",
    "icon": "📗",
    "name": {
      "en": "Excel Workbook Viewer",
      "ja": "Excelビューア",
      "zh": "Excel 查看器",
      "de": "Excel-Arbeitsmappen-Viewer",
      "es": "Visor de libros de Excel"
    },
    "desc": {
      "en": "Open and browse an Excel workbook: switch sheets, no editing.",
      "ja": "Excelブックを開いて閲覧。シート切替、編集はしません。",
      "zh": "打开并浏览 Excel 工作簿，可切换工作表，不支持编辑。",
      "de": "Excel-Arbeitsmappe öffnen und ansehen, Blätter wechseln, keine Bearbeitung.",
      "es": "Abre y consulta un libro de Excel, cambia de hoja, sin edición."
    }
  },
  {
    "slug": "csv-to-xlsx",
    "icon": "📥",
    "name": {
      "en": "CSV to XLSX",
      "ja": "CSV→XLSX統合",
      "zh": "CSV 合并为 XLSX",
      "de": "CSV zu XLSX zusammenführen",
      "es": "CSV a XLSX"
    },
    "desc": {
      "en": "Combine multiple CSV files into one Excel workbook, one sheet per file.",
      "ja": "複数CSVを1ファイル1シートで1つのExcelに統合。",
      "zh": "将多个 CSV 文件合并为一个 Excel 工作簿，一文件一工作表。",
      "de": "Führt mehrere CSV-Dateien zu einer Excel-Arbeitsmappe zusammen, ein Blatt pro Datei.",
      "es": "Combina varios archivos CSV en un libro de Excel, una hoja por archivo."
    }
  },
  {
    "slug": "xlsx-to-csv",
    "icon": "📤",
    "name": {
      "en": "XLSX to CSV",
      "ja": "XLSX→CSV分割",
      "zh": "XLSX 转 CSV",
      "de": "XLSX zu CSV",
      "es": "XLSX a CSV"
    },
    "desc": {
      "en": "Split an Excel workbook into one CSV per sheet, zipped.",
      "ja": "Excelブックを1シート1CSVに分割してZIPで出力。",
      "zh": "将 Excel 工作簿按工作表拆分为多个 CSV，打包为 ZIP。",
      "de": "Teilt eine Excel-Arbeitsmappe in je eine CSV pro Blatt auf, als ZIP.",
      "es": "Divide un libro de Excel en un CSV por hoja, comprimido en ZIP."
    }
  }
];

/** This tool's own engineering-notes article slug (/blog/<slug>/), or null if none is published yet. */
export const BLOG_SLUG: string | null = 'csv-viewer';
